version: "3.8"

services:  
  go-application:
    container_name: go-application
    build: .
    ports: 
      - 8081:8080
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=Eoo{~]23MvDq'V-^
      - DB_DB=alterra
      - DB_HOST=34.101.247.240
      - DB_PORT=3306
    restart: on-failure