version: "3.8"

services:  
  go-application:
    container_name: go-application
    build: .
    ports: 
      - 8081:8080
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=secret-password
      - DB_DB=alterra
      - DB_HOST=test.cuuqzafibs9v.ap-southeast-1.rds.amazonaws.com
      - DB_PORT=3306
    restart: on-failure